# Generated by Django 4.0.4 on 2022-05-31 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name_author', models.CharField(max_length=50)),
                ('content_text', models.TextField()),
                ('data_publish', models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 31, 13, 23, 49, 236971, tzinfo=utc))),
                ('data_edit_publish', models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 31, 13, 23, 49, 236971, tzinfo=utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
    ]
