# Generated by Django 4.0.4 on 2022-08-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_comment_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content_text',
            new_name='body',
        ),
    ]
